all:
	gcc -lm lucas_santana4_exercicio_1a5.c -o lucas_santana4_exercicio_1a5
	gcc -lm lucas_santana4_exercicio_6a8.c -o lucas_santana4_exercicio_6a8
	gcc -lm lucas_santana4_exercicio_9a11.c -o lucas_santana4_exercicio_9a11

clean:
	rm -vf lucas_santana4_exercicio_1a5 lucas_santana4_exercicio_6a8 lucas_santana4_exercicio_9a11








